Rename provision config instance
opensearch-project/opensearch-benchmark pull request #400
Opened 2023-10-28 06:40 UTC by cgchinmay

### Description
[Describe what this change achieves]
renames provision_config_instance to cluster-config

### Issues Resolved
[List any issues this PR will resolve]
310

### Testing
- [ ] New functionality includes testing

[Describe how this change was tested]
validated with `make test` and `make it`
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-10-31 16:12 UTC, IanHoang commented on osbenchmark/benchmark.py
> +        help=f"Define the cluster_config to use. List possible "
Nit: Update `cluster_config` --> `cluster-config` to keep consistency in help texts

2023-10-31 16:13 UTC, IanHoang commented on osbenchmark/benchmark.py
> +        help="Define a comma-separated list of key:value pairs that are injected verbatim as variables for the cluster_config.",
Nit: `cluster_config` --> `cluster-config`

2023-10-31 16:14 UTC, IanHoang commented on osbenchmark/benchmark.py
> +        help=f"Define the cluster_config to use. List possible "
Nit: `cluster_config` and `cluster_configs` --> `cluster-config` and `cluster-config`

2023-10-31 16:14 UTC, IanHoang commented on osbenchmark/benchmark.py
> +        help="Define the path to the cluster_config and plugin configurations to use.")
Nit: `cluster_config` --> `cluster-config`

2023-10-31 16:18 UTC, IanHoang requested changes
Left some minor suggestions but overall looks good to me! Were you able to test this? Could you provide a sample output of the help text and a brief run with a cluster-config to ensure that it works? 

When we merge this in, we'll merge this into a separate branch first since these changes are considered breaking-changes. Thus, we don't want to merge this into mainline yet until we're ready to release OSB 2.0.0

2023-10-31 16:23 UTC, cgchinmay commented
Yes, I will make the suggested changes and share output

On Tue, Oct 31, 2023, 9:18 AM Ian Hoang ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Left some minor suggestions but overall looks good to me! Were you able to
> test this? Could you provide a sample output of the help text and a brief
> run with a cluster-config to ensure that it works?
>
> When we merge this in, we'll merge this into a separate branch first since
> these changes are considered breaking-changes. Thus, we don't want to merge
> this into mainline yet until we're ready to release OSB 2.0.0
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/opensearch-project/opensearch-benchmark/pull/400#pullrequestreview-1706737627>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABUCKL7KFHNA6SWEC7NRW7TYCEQE3AVCNFSM6AAAAAA6T2DUD2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMBWG4ZTONRSG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> .com>
>

2023-11-09 20:12 UTC, IanHoang approved these changes

2023-11-14 21:07 UTC, merged