Renaming all occurrences of test-procedure to procedure
opensearch-project/opensearch-benchmark pull request #421
Opened 2023-12-05 18:19 UTC by beaioun

### Description
Renaming all occurrences of the name test-procedure and test_procedure to procedure, class name TestProcedure to Procedure

### Issues Resolved
issue #308

### Testing
- [ ] New functionality includes testing

### Describe how this change was tested
a unit test was run and more tests will be conducted for the following commit on other test-procedure names.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-12-05 21:06 UTC, IanHoang commented on osbenchmark/metrics.py
> +        :param test_procedure_name: Procedure name.
test_procedure_name -> procedure_name

2023-12-05 21:10 UTC, IanHoang commented on tests/workload/loader_test.py
>          t = workload.Workload(name="u", test_procedures=[another_test_procedure, default_test_procedure],
You'll need to also change occurrences like `test_procedures`, `another_test_prcedure`, `default_test_procedure`. However, I think your approach is good if you plan to do a commit for each variation in this PR. For example, in the latest commit, you're renaming only `TestProcedure` -> `Procedure`. In subsequent commits, you can dedicate a commit to renaming instances of `test_procedure` or `test-procedure`.

2023-12-05 21:10 UTC, IanHoang commented on tests/workload/loader_test.py
> +        self.assertEqual("Workload 'unittest' is invalid. Procedure 'default-test_procedure' contains multiple tasks"
`default-test_procedure` will also be corrected when you do a replace for `test_procedure` -> `procedure`

2023-12-05 21:11 UTC, IanHoang requested changes
Thanks for this! This is the final piece to the puzzle for our renaming components initiative. I like how you're creating different commits to address the different variations of Test Procedures.

2023-12-05 21:44 UTC, beaioun commented
> Thanks for this! This is the final piece to the puzzle for our renaming components initiative. I left a few comments. I like how you're creating different commits to address the different variations of Test Procedures.

Yes Ian, that's the plan. I will finish working on the rest of naming tomorrow. And maybe test about its interaction with the workload to see if it will run into any issues.

2023-12-07 00:18 UTC, beaioun commented
Hey, @IanHoang I did manage to rename every occurrence in the repo but failed the integration test over this Error: `[ERROR] Cannot execute-test. Error in test execution orchestrator (Workload 'geonames' is invalid. You must define 'procedure', 'procedures', or 'schedule' but none is specified.)` or something similar. I couldn't trace the root cause of this error but it seems to lead to workload/loader.py which is expected as we have discussed.
The next step is maybe to make changes to the workload repo in a safe manner.

2023-12-20 19:12 UTC, IanHoang commented
Update: Currently working with Mingyang (@beaioun) on testing these changes out

2024-01-19 17:34 UTC, IanHoang commented
Closing this PR as a duplicate has been created

2024-01-19 17:34 UTC, closed without merging