Added runners to register and deploy ml-model
opensearch-project/opensearch-benchmark pull request #497
Opened 2024-03-30 06:19 UTC by vpehkone

### Description
Added runners DeletePipeline, DeleteMlModel, RegisterMlModel and DeployMlModel. So that we can run the new workload semantic_search, that does indexing and search with vector embedding.

### Issues Resolved
https://github.com/opensearch-project/opensearch-benchmark-workloads/issues/198

### Testing
Tested by executing the neural_search workload

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-04-03 15:03 UTC, IanHoang commented on osbenchmark/worker_coordinator/runner.py
> +            pass # no current pipeline
Might be useful to still add a logging statement that states that there is no current pipeline to delete before swallowing the exception.

2024-04-03 15:07 UTC, IanHoang commented on osbenchmark/worker_coordinator/runner.py
> +            pass # no current model
Recommend adding a logging statement that there is no current model before swallowing

2024-04-03 15:08 UTC, IanHoang commented on osbenchmark/worker_coordinator/runner.py
> +            pass
Recommend adding logging statement for exception here.

2024-04-03 15:10 UTC, IanHoang commented on osbenchmark/worker_coordinator/runner.py
> +            "size": 1000
Will we ever need to change the size parameter? If so, might be useful to have a variable that references its value

2024-04-03 15:27 UTC, IanHoang commented on osbenchmark/worker_coordinator/runner.py
> +            pass
Pylint also suggests that this is a bare except.
```
osbenchmark/worker_coordinator/runner.py:1288:8: W0702: No exception type(s) specified (bare-except)
osbenchmark/worker_coordinator/runner.py:2404:8: W0702: No exception type(s) specified (bare-except)
osbenchmark/worker_coordinator/runner.py:2444:8: W0702: No exception type(s) specified (bare-except)
```

2024-04-03 15:27 UTC, IanHoang commented on osbenchmark/worker_coordinator/runner.py
> +            pass # no current model
Pylint also suggests that this is a bare except.
```
osbenchmark/worker_coordinator/runner.py:1288:8: W0702: No exception type(s) specified (bare-except)
osbenchmark/worker_coordinator/runner.py:2404:8: W0702: No exception type(s) specified (bare-except)
osbenchmark/worker_coordinator/runner.py:2444:8: W0702: No exception type(s) specified (bare-except)
```

2024-04-03 15:28 UTC, IanHoang commented on osbenchmark/worker_coordinator/runner.py
> +            pass # no current pipeline
Pylint also suggests that this is a bare except.
```
osbenchmark/worker_coordinator/runner.py:1288:8: W0702: No exception type(s) specified (bare-except)
osbenchmark/worker_coordinator/runner.py:2404:8: W0702: No exception type(s) specified (bare-except)
osbenchmark/worker_coordinator/runner.py:2444:8: W0702: No exception type(s) specified (bare-except)
```

2024-04-03 15:29 UTC, IanHoang requested changes
Please add an exception class and logging statement to except clauses

2024-04-12 22:12 UTC, vpehkone commented
@IanHoang Can you please review, I have addressed the issues.

2024-04-19 22:02 UTC, IanHoang approved these changes

2024-04-19 23:03 UTC, merged