Refactor aggregate
opensearch-project/opensearch-benchmark pull request #708
Opened 2024-12-10 22:00 UTC by OVI3D0

Description
Refactor the aggregate feature to make individual functions more single-purpose, as well as renaming variables and adding more explanatory comments.

Testing
 New functionality includes testing
make test

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-12-16 23:01 UTC, IanHoang requested changes

2024-12-16 23:01 UTC, IanHoang commented on osbenchmark/aggregator.py
> +        for task in self.loaded_workload.find_test_procedure_or_default(self.test_procedure_name).schedule:
Much more clean!

2024-12-16 23:01 UTC, IanHoang commented on osbenchmark/aggregator.py
> +    def build_aggregated_results(self):
We should add a return type hint

2024-12-17 20:04 UTC, OVI3D0 commented on osbenchmark/aggregator.py
> +    def update_config_object(self, test_execution):
True, added type hints to all the functions now!

2024-12-17 20:06 UTC, OVI3D0 commented on osbenchmark/aggregator.py
>          def get_nested_value(obj: Dict[str, Any], path: List[str]) -> Any:
You're right, renamed a bunch of variables in the aggregate_json_by_key function. Hopefully it's more clear now

2024-12-17 20:06 UTC, OVI3D0 commented on osbenchmark/aggregator.py
>              if not objects:
renamed + added comments now! lmk what you think

2024-12-17 20:07 UTC, OVI3D0 commented on osbenchmark/aggregator.py
> +    def build_aggregated_results(self):
Done ✅

2024-12-18 15:52 UTC, IanHoang approved these changes
LGTM, thanks for making these changes

2024-12-18 15:52 UTC, merged