Rename execute to 'run'
opensearch-project/opensearch-benchmark pull request #720
Opened 2024-12-30 20:03 UTC by OVI3D0

### Description
Renames instances of 'execute' to 'run', including 'execute-test' 'TestExecution*', etc. Please comment if I missed any instances!

### Issues Resolved
#307 

### Testing
- [ ] New functionality includes testing

Tested with `make test` and by running test runs + aggregations with a provisioned cluster.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2025-01-22 17:55 UTC, IanHoang commented on osbenchmark/test_run_orchestrator.py
> +    Describes a whole run pipeline. A pipeline can consist of one or more steps. Each pipeline should contain roughly of the following
Nit: `a whole test run pipeline`

2025-01-22 18:33 UTC, IanHoang commented on scripts/analyze.py
> +# stored in ~/.benchmark/benchmarks/test_runs/test_run_TS/).
This can be corrected: `stored in ~/.benchmark/benchmarks/test_runs/<test_run_id>/)`

2025-01-22 19:15 UTC, IanHoang commented on tests/metrics_test.py
> +        self.metrics_store.open(InMemoryMetricsStoreTests.test_run_ID, InMemoryMetricsStoreTests.test_run_TIMESTAMP,
`TEST_RUN_ID` and `TEST_RUN_TIMESTAMP`

2025-01-22 19:15 UTC, IanHoang commented on tests/metrics_test.py
> +    test_run_ID = "fb26018b-428d-4528-b36b-cf8c54a303ec"
Should uppercase all

2025-01-22 19:16 UTC, IanHoang commented on tests/metrics_test.py
> +                            test_run_timestamp=FileTestRunStoreTests.test_run_TIMESTAMP,
Should have all caps for these too

2025-01-22 19:16 UTC, IanHoang commented on tests/metrics_test.py
> +            self.test_run_store.find_by_test_run_id(FileTestRunStoreTests.test_run_ID)
Should have all caps for this

2025-01-22 19:16 UTC, IanHoang commented on tests/metrics_test.py
> +        self.cfg.add(config.Scope.application, "system", "time.start", FileTestRunStoreTests.test_run_TIMESTAMP)
Needs all caps

2025-01-22 19:17 UTC, IanHoang commented on tests/metrics_test.py
Needs all caps

2025-01-22 19:17 UTC, IanHoang commented on tests/metrics_test.py
> +        self.metrics_store.open(InMemoryMetricsStoreTests.test_run_ID, InMemoryMetricsStoreTests.test_run_TIMESTAMP,
All caps

2025-01-22 19:17 UTC, IanHoang commented on tests/metrics_test.py
> +        self.metrics_store.open(InMemoryMetricsStoreTests.test_run_ID, InMemoryMetricsStoreTests.test_run_TIMESTAMP,
All caps

2025-01-22 19:17 UTC, IanHoang commented on tests/metrics_test.py
> +        self.metrics_store.open(InMemoryMetricsStoreTests.test_run_ID, InMemoryMetricsStoreTests.test_run_TIMESTAMP,
All caps

2025-01-22 19:18 UTC, IanHoang commented on tests/metrics_test.py
> +                "test-run-id": OsResultsStoreTests.test_run_ID,
Ensure casing is uniform

2025-01-22 21:27 UTC, IanHoang commented on osbenchmark/benchmark.py
> +    elif what == "test_runs":
How do you feel about switching this to `test-runs` since it's front-facing and being invoked by the user in `opensearch-benchmark list test_runs`? If we go with a hyphenated approach, we should also update the local directory where they are being stored as `test-runs` directory.

2025-01-22 21:30 UTC, IanHoang commented on osbenchmark/metrics.py
> +        result = self.client.search(index="%s*" % EsTestRunStore.INDEX_PREFIX, body=query)
EsTestRunStore  -> OsTestRunStore

2025-01-22 21:31 UTC, IanHoang commented on osbenchmark/metrics.py
> +        result = self.client.search(index="%s*" % EsTestRunStore.INDEX_PREFIX, body=query)
EsTestRunStore -> OsTestRunStore

2025-01-22 21:31 UTC, IanHoang commented on osbenchmark/metrics.py
> +        return f"{EsTestRunStore.INDEX_PREFIX}{test_run_timestamp:%Y-%m}"
EsTestRunStore -> OsTestRunStore

2025-01-22 21:31 UTC, IanHoang commented on osbenchmark/metrics.py
> +            doc_type=EsTestRunStore.test_run_DOC_TYPE,
1. All caps for TEST_RUN_DOC_TYPE
2. EsTestRunStore -> OsTestRunStore

2025-01-22 21:31 UTC, IanHoang commented on osbenchmark/metrics.py
> +class EsTestRunStore(TestRunStore):
EsTestRunStore -> OsTestRunStore

2025-01-22 21:59 UTC, IanHoang commented on osbenchmark/metrics.py
> +    test_run_DOC_TYPE = "_doc"
Needs All caps

2025-01-22 23:09 UTC, IanHoang commented on osbenchmark/metrics.py
> +        return CompositeTestRunStore(EsTestRunStore(cfg), FileTestRunStore(cfg))
EsTestRunStore -> OsTestRunStore

2025-01-22 23:11 UTC, IanHoang requested changes
Left comments. We can sync up on the front-facing `test_runs` to `test-runs` if you'd like

2025-01-23 18:26 UTC, OVI3D0 commented on osbenchmark/benchmark.py
> +    elif what == "test_runs":
Personally, I'm on board with this. When I was first working with OSB, I'd often hit `list test-executions` instead of `list test_executions`. I think hyphens are more natural when it comes to running commands. I added this change for now but I think we should also get @gkamat opinion on this

2025-01-23 19:01 UTC, IanHoang commented on osbenchmark/benchmark.py
> +    elif what == "test_runs":
If we decide to go forth with this change, we would also have to do this for `aggregated_results` but we could leave that for a separate PR..

2025-02-06 19:50 UTC, IanHoang approved these changes

2025-02-06 19:50 UTC, IanHoang commented on osbenchmark/benchmark.py
> +    elif what == "test_runs":
Spoke offline: we have decided to go forth with underscores for arguments to keep things consistent

2025-02-06 19:52 UTC, merged